dist: xenial
language: python

branches:
  only:
    - master

python:
  - "3.6"

services:
  - xvfb

install:
  - sh .travis/install

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

script:
  - python -m pytest tests/